package com.example.miaosha.entity;

import lombok.Data;

@Data
public class UserInfo {/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.id
	 * @mbg.generated  Tue Mar 12 11:01:04 CST 2019
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.name
	 * @mbg.generated  Tue Mar 12 11:01:04 CST 2019
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.gender
	 * @mbg.generated  Tue Mar 12 11:01:04 CST 2019
	 */
	private Short gender;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.age
	 * @mbg.generated  Tue Mar 12 11:01:04 CST 2019
	 */
	private Integer age;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.telephone
	 * @mbg.generated  Tue Mar 12 11:01:04 CST 2019
	 */
	private String telephone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.register_mode
	 * @mbg.generated  Tue Mar 12 11:01:04 CST 2019
	 */
	private String registerMode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.third_party_id
	 * @mbg.generated  Tue Mar 12 11:01:04 CST 2019
	 */
	private String thirdPartyId;




}