package com.example.miaosha.dao;

import com.example.miaosha.entity.Promo;

public interface PromoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table promo
	 * @mbg.generated  Mon Mar 25 13:52:16 CST 2019
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table promo
	 * @mbg.generated  Mon Mar 25 13:52:16 CST 2019
	 */
	int insert(Promo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table promo
	 * @mbg.generated  Mon Mar 25 13:52:16 CST 2019
	 */
	int insertSelective(Promo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table promo
	 * @mbg.generated  Mon Mar 25 13:52:16 CST 2019
	 */
	Promo selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table promo
	 * @mbg.generated  Mon Mar 25 13:52:16 CST 2019
	 */
	int updateByPrimaryKeySelective(Promo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table promo
	 * @mbg.generated  Mon Mar 25 13:52:16 CST 2019
	 */
	int updateByPrimaryKey(Promo record);
	
	
	Promo selectByItemId(Integer itemId);
}