package com.example.miaosha.dao;

import com.example.miaosha.entity.UserPassword;

public interface UserPasswordMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_password
	 * @mbg.generated  Wed Mar 13 16:11:51 CST 2019
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_password
	 * @mbg.generated  Wed Mar 13 16:11:51 CST 2019
	 */
	int insert(UserPassword record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_password
	 * @mbg.generated  Wed Mar 13 16:11:51 CST 2019
	 */
	int insertSelective(UserPassword record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_password
	 * @mbg.generated  Wed Mar 13 16:11:51 CST 2019
	 */
	UserPassword selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_password
	 * @mbg.generated  Wed Mar 13 16:11:51 CST 2019
	 */
	int updateByPrimaryKeySelective(UserPassword record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_password
	 * @mbg.generated  Wed Mar 13 16:11:51 CST 2019
	 */
	int updateByPrimaryKey(UserPassword record);

	UserPassword selectByUserId(Integer userId);
}