package com.example.miaosha.dao;


import com.example.miaosha.entity.UserInfo;


public interface UserInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_info
	 * @mbg.generated  Wed Mar 13 16:11:51 CST 2019
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_info
	 * @mbg.generated  Wed Mar 13 16:11:51 CST 2019
	 */
	int insert(UserInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_info
	 * @mbg.generated  Wed Mar 13 16:11:51 CST 2019
	 */
	int insertSelective(UserInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_info
	 * @mbg.generated  Wed Mar 13 16:11:51 CST 2019
	 */
	UserInfo selectByPrimaryKey(Integer id);
	
	
	UserInfo selectByTelphone(String telphone);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_info
	 * @mbg.generated  Wed Mar 13 16:11:51 CST 2019
	 */
	int updateByPrimaryKeySelective(UserInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_info
	 * @mbg.generated  Wed Mar 13 16:11:51 CST 2019
	 */
	int updateByPrimaryKey(UserInfo record);
}