package com.example.miaosha.dao;

import com.example.miaosha.entity.UserPassword;

public interface UserPasswordMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_password
	 * @mbg.generated  Tue Mar 12 11:01:04 CST 2019
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_password
	 * @mbg.generated  Tue Mar 12 11:01:04 CST 2019
	 */
	int insert(UserPassword record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_password
	 * @mbg.generated  Tue Mar 12 11:01:04 CST 2019
	 */
	int insertSelective(UserPassword record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_password
	 * @mbg.generated  Tue Mar 12 11:01:04 CST 2019
	 */
	UserPassword selectByPrimaryKey(Integer id);
	
	UserPassword selectByUserId(Integer userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_password
	 * @mbg.generated  Tue Mar 12 11:01:04 CST 2019
	 */
	int updateByPrimaryKeySelective(UserPassword record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_password
	 * @mbg.generated  Tue Mar 12 11:01:04 CST 2019
	 */
	int updateByPrimaryKey(UserPassword record);
}