package com.example.miaosha.dao;

import com.example.miaosha.entity.UserInfo;

public interface UserInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_info
	 * @mbg.generated  Mon Mar 11 19:00:22 CST 2019
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_info
	 * @mbg.generated  Mon Mar 11 19:00:22 CST 2019
	 */
	int insert(UserInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_info
	 * @mbg.generated  Mon Mar 11 19:00:22 CST 2019
	 */
	int insertSelective(UserInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_info
	 * @mbg.generated  Mon Mar 11 19:00:22 CST 2019
	 */
	UserInfo selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_info
	 * @mbg.generated  Mon Mar 11 19:00:22 CST 2019
	 */
	int updateByPrimaryKeySelective(UserInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_info
	 * @mbg.generated  Mon Mar 11 19:00:22 CST 2019
	 */
	int updateByPrimaryKey(UserInfo record);
}